/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BLLTaiKhoan;
import DTO.DTOTaiKhoan;
import javax.swing.JOptionPane;

/**
 *
 * @author 3dx
 */
public class GUIDangKi extends javax.swing.JFrame {
    BLLTaiKhoan BLLtk = new BLLTaiKhoan();
    /**
     * Creates new form GUIDangKi
     */
    public GUIDangKi() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        textRepass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textTK = new javax.swing.JTextField();
        buttonTaoTK = new javax.swing.JButton();
        labelBack = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ĐĂNG KÍ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 19, -1, -1));
        getContentPane().add(textPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 240, 40));

        jLabel2.setText("Tài khoản");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 92, -1, -1));
        getContentPane().add(textRepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 240, 40));

        jLabel3.setText("Mật khẩu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 146, -1, -1));

        jLabel4.setText("Nhập lại mật khẩu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        textTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTKActionPerformed(evt);
            }
        });
        getContentPane().add(textTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 82, 245, 36));

        buttonTaoTK.setBackground(new java.awt.Color(0, 204, 255));
        buttonTaoTK.setText("Tạo tài khoản");
        buttonTaoTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTaoTKActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTaoTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 276, 110, 40));

        labelBack.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        labelBack.setText("Quay lại đăng nhập");
        labelBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBackMouseClicked(evt);
            }
        });
        getContentPane().add(labelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 322, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, -130, 690, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTKActionPerformed

    private void labelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBackMouseClicked
        // TODO add your handling code here:
        GUIDangNhap dn_gui = new GUIDangNhap();
        dn_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_labelBackMouseClicked

    private void buttonTaoTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTaoTKActionPerformed
        // TODO add your handling code here:
        try {
            if(textTK.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập tài khoản!");
            }
            else if(textPass.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập mật khẩu!");
            }
            else if(textRepass.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập lại mật khẩu!");
            }
            else if( Integer.valueOf(textRepass.getText())!= Integer.valueOf(textPass.getText())){
                JOptionPane.showMessageDialog(null, "Mật khẩu không trùng khớp!");
            }
            else{
                DTOTaiKhoan tk = new DTOTaiKhoan();
                tk.setTaikhoan(textTK.getText());
                tk.setMatkhau(textPass.getText());
                JOptionPane.showMessageDialog(this,BLLtk.BLLthem(tk));
                textTK.setText("");
                textPass.setText("");
                textRepass.setText("");
            }
        } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }  
    }//GEN-LAST:event_buttonTaoTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDangKi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDangKi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTaoTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelBack;
    private javax.swing.JPasswordField textPass;
    private javax.swing.JPasswordField textRepass;
    private javax.swing.JTextField textTK;
    // End of variables declaration//GEN-END:variables
}
