package GUI;

import BLL.BLLNhanVien;
import DTO.DTONhanVien;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Phuc Nguyen
 */

public class GUINhanVien extends javax.swing.JFrame {
    DefaultTableModel model;
    BLLNhanVien BLLnv = new BLLNhanVien();
    public GUINhanVien() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tableNV.getModel();
        Color col = new Color(51,51,51);
        getContentPane().setBackground(col);
        loadNVList();
        model = (DefaultTableModel) tableNV.getModel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelManv = new javax.swing.JLabel();
        labelHoten = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labelSodienthoai = new javax.swing.JLabel();
        textManv = new javax.swing.JTextField();
        textHoten = new javax.swing.JTextField();
        textDate = new javax.swing.JTextField();
        textSodienthoai = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        BAddNV = new javax.swing.JButton();
        BXoaNV = new javax.swing.JButton();
        BSuaNhanvien = new javax.swing.JButton();
        labelDiachi = new javax.swing.JLabel();
        textDiachi = new javax.swing.JTextField();
        labelGender = new javax.swing.JLabel();
        ComboBoxGenderNV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textLuong = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchMaNv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSearchTenNV = new javax.swing.JTextField();
        BtnSeachNV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNV = new javax.swing.JTable();
        buttonHuyTim = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên");
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        labelManv.setForeground(new java.awt.Color(255, 255, 255));
        labelManv.setText(" Mã Nhân viên: ");

        labelHoten.setForeground(new java.awt.Color(255, 255, 255));
        labelHoten.setText("Họ Tên Nhân Viên: ");

        labelDate.setForeground(new java.awt.Color(255, 255, 255));
        labelDate.setText("Ngày Sinh: ");

        labelSodienthoai.setForeground(new java.awt.Color(255, 255, 255));
        labelSodienthoai.setText("Số Điện Thoại");

        textHoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHotenActionPerformed(evt);
            }
        });

        textDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDateActionPerformed(evt);
            }
        });

        textSodienthoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSodienthoaiActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        BAddNV.setBackground(new java.awt.Color(102, 102, 102));
        BAddNV.setForeground(new java.awt.Color(255, 255, 255));
        BAddNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_add_20px.png"))); // NOI18N
        BAddNV.setText("Thêm Nhân Viên");
        BAddNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BAddNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddNVActionPerformed(evt);
            }
        });

        BXoaNV.setBackground(new java.awt.Color(102, 102, 102));
        BXoaNV.setForeground(new java.awt.Color(255, 255, 255));
        BXoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_cancel_20px.png"))); // NOI18N
        BXoaNV.setText("Xóa Nhân Viên");
        BXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BXoaNVActionPerformed(evt);
            }
        });

        BSuaNhanvien.setBackground(new java.awt.Color(102, 102, 102));
        BSuaNhanvien.setForeground(new java.awt.Color(255, 255, 255));
        BSuaNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_maintenance_20px.png"))); // NOI18N
        BSuaNhanvien.setText("Sửa Nhân Viên");
        BSuaNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSuaNhanvienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BAddNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(BXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(BSuaNhanvien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAddNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BSuaNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        labelDiachi.setForeground(new java.awt.Color(255, 255, 255));
        labelDiachi.setText("Địa Chỉ: ");

        textDiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDiachiActionPerformed(evt);
            }
        });

        labelGender.setForeground(new java.awt.Color(255, 255, 255));
        labelGender.setText("Giới Tính");

        ComboBoxGenderNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        ComboBoxGenderNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxGenderNVActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lương: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelManv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(ComboBoxGenderNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelHoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelSodienthoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textLuong)
                    .addComponent(textHoten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(textManv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(textDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(textDiachi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSodienthoai))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(labelManv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textManv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSodienthoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textSodienthoai, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxGenderNV)
                    .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã Nhân Viên:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên Nhân Viên: ");

        BtnSeachNV.setBackground(new java.awt.Color(102, 102, 102));
        BtnSeachNV.setForeground(new java.awt.Color(255, 255, 255));
        BtnSeachNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_search_20px_1.png"))); // NOI18N
        BtnSeachNV.setText("Search");
        BtnSeachNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeachNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchMaNv)
                    .addComponent(txtSearchTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(BtnSeachNV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchMaNv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSeachNV)
                .addGap(34, 34, 34))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NHÂN VIÊN");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/backicon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Ngày sinh", "Địa chỉ", "Lương", "SĐT", "Giới tính"
            }
        ));
        tableNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableNV);

        buttonHuyTim.setBackground(new java.awt.Color(102, 102, 102));
        buttonHuyTim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonHuyTim.setForeground(new java.awt.Color(255, 255, 255));
        buttonHuyTim.setText("Reset");
        buttonHuyTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHuyTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(388, 388, 388)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonHuyTim)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonHuyTim)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textHotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHotenActionPerformed

    private void textDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDateActionPerformed

    private void textSodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSodienthoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSodienthoaiActionPerformed

    public void loadNVList(){
        model = new DefaultTableModel();
        model.addColumn("Mã NV");
        model.addColumn("Họ tên");
        model.addColumn("Ngày Sinh");
        model.addColumn("Địa chỉ");
        model.addColumn("Lương");
        model.addColumn("SĐT");
        model.addColumn("Giới tính");
        tableNV.setModel(model);
        ArrayList<DTONhanVien> arr = new ArrayList<DTONhanVien>();
        arr = BLLnv.BLLgetDL();
        for(int i = 0; i < arr.size(); i++){
            DTONhanVien nv = arr.get(i);
            String manv = nv.getMaNV();
            String ten = nv.getTenNV();
            String gioitinh = nv.getSex();
            String ngaysinh = nv.getNgaySinh();
            String diachi = nv.getDiaChi();
            String sdt = nv.getSDT();
            Float luong = nv.getLuong();
            Object[] row = {manv,ten,ngaysinh,diachi,luong,sdt,gioitinh};
            model.addRow(row);
        }
    }
    
    private void BAddNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddNVActionPerformed
         // TODO add your handling code here:
        try {
            if(textManv.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập mã nhân viên!");
            }
            else if(textHoten.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập họ tên nhân viên!");
            }
            else if(textDate.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập ngày sinh nhân viên");
            }
            else if(textDiachi.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập địa chỉ nhân viên!");
            }
            else if(textLuong.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập lương nhân viên!");
            }
            else if(textSodienthoai.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập số điện thoại nhân viên!");
            }
            else{
                DTONhanVien nv = new DTONhanVien();
                nv.setMaNV(textManv.getText());
                nv.setTenNV(textHoten.getText());
                nv.setNgaySinh(textDate.getText());
                nv.setDiaChi(textDiachi.getText());
                nv.setLuong(Float.valueOf(textLuong.getText()));
                nv.setSex((String) ComboBoxGenderNV.getSelectedItem());
                nv.setSDT(textSodienthoai.getText());
                JOptionPane.showMessageDialog(this,BLLnv.BLLthem(nv));
                loadNVList();
                textManv.setText("");textHoten.setText("");textDate.setText("");textDiachi.setText("");textLuong.setText("");textSodienthoai.setText("");
            }  
        } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        } 
    }//GEN-LAST:event_BAddNVActionPerformed

    private void BXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BXoaNVActionPerformed
        // TODO add your handling code here:
        int i = tableNV.getSelectedRow();
        DTONhanVien nv = new DTONhanVien();
        if(i >= 0){
            nv.setMaNV(model.getValueAt(i, 0).toString());
            nv.setTenNV(model.getValueAt(i, 1).toString());
            nv.setNgaySinh(model.getValueAt(i, 2).toString());
            nv.setDiaChi(model.getValueAt(i, 3).toString());
            nv.setLuong(Float.valueOf(model.getValueAt(i, 4).toString()));
            nv.setSDT(model.getValueAt(i, 5).toString());
            nv.setSex(model.getValueAt(i, 6).toString());
        }
        JOptionPane.showMessageDialog(this,BLLnv.BLLxoa(nv));
        loadNVList();
        textManv.setText("");textHoten.setText("");textDate.setText("");textDiachi.setText("");textLuong.setText("");textSodienthoai.setText("");
    }//GEN-LAST:event_BXoaNVActionPerformed

    private void textDiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDiachiActionPerformed

    private void ComboBoxGenderNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxGenderNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxGenderNVActionPerformed

    private void BSuaNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSuaNhanvienActionPerformed
        // TODO add your handling code here:
        int i = tableNV.getSelectedRow();
        DTONhanVien nv = new DTONhanVien();
        if(i >= 0){
            nv.setMaNV(textManv.getText());
            nv.setTenNV(textHoten.getText());
            nv.setNgaySinh(textDate.getText());
            nv.setDiaChi(textDiachi.getText());
            nv.setLuong(Float.valueOf(textLuong.getText()));
            nv.setSDT(textSodienthoai.getText());
            nv.setSex(String.valueOf(ComboBoxGenderNV.getSelectedItem()));
        }
        JOptionPane.showMessageDialog(this,BLLnv.BLLsua(nv));
        loadNVList();
        textManv.setText("");textHoten.setText("");textDate.setText("");textDiachi.setText("");textLuong.setText("");textSodienthoai.setText("");
    }//GEN-LAST:event_BSuaNhanvienActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GUITrangChu tc_gui = new GUITrangChu();
        tc_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnSeachNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeachNVActionPerformed
        // TODO add your handling code here:
        DTONhanVien nv = BLLnv.BLLtim(txtSearchMaNv.getText().trim());
        if(nv != null){
            model = new DefaultTableModel();
            model.addColumn("Mã NV");
            model.addColumn("Tên NV");
            model.addColumn("Ngày sinh");
            model.addColumn("Địa chỉ");
            model.addColumn("Lương");
            model.addColumn("SĐT");
            model.addColumn("Giới tính");
            tableNV.setModel(model);
            Object[] row = {nv.getMaNV(),nv.getTenNV(),nv.getNgaySinh(),nv.getDiaChi(),nv.getLuong(),nv.getSDT(),nv.getSex()};
            model.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã nhân viên");
        }
    }//GEN-LAST:event_BtnSeachNVActionPerformed

    private void buttonHuyTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHuyTimActionPerformed
        // TODO add your handling code here:
        loadNVList();
    }//GEN-LAST:event_buttonHuyTimActionPerformed

    private void tableNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNVMouseClicked
        // TODO add your handling code here:
        int i=tableNV.getSelectedRow();
        if (i>=0){
            textManv.setText(model.getValueAt(i, 0).toString().trim()); 
            textHoten.setText(model.getValueAt(i, 1).toString());
            textDate.setText(model.getValueAt(i, 2).toString());
            textDiachi.setText(model.getValueAt(i, 3).toString());
            textLuong.setText(model.getValueAt(i, 4).toString());
            textSodienthoai.setText(model.getValueAt(i, 5).toString());
            ComboBoxGenderNV.setSelectedItem(model.getValueAt(i, 6).toString());
        }
    }//GEN-LAST:event_tableNVMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAddNV;
    private javax.swing.JButton BSuaNhanvien;
    private javax.swing.JButton BXoaNV;
    private javax.swing.JButton BtnSeachNV;
    private javax.swing.JComboBox<String> ComboBoxGenderNV;
    private javax.swing.JButton buttonHuyTim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDiachi;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelHoten;
    private javax.swing.JLabel labelManv;
    private javax.swing.JLabel labelSodienthoai;
    private javax.swing.JTable tableNV;
    private javax.swing.JTextField textDate;
    private javax.swing.JTextField textDiachi;
    private javax.swing.JTextField textHoten;
    private javax.swing.JTextField textLuong;
    private javax.swing.JTextField textManv;
    private javax.swing.JTextField textSodienthoai;
    private javax.swing.JTextField txtSearchMaNv;
    private javax.swing.JTextField txtSearchTenNV;
    // End of variables declaration//GEN-END:variables
}

