/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BLLNhaCungCap;
import DTO.DTONhaCungCap;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 3dx
 */
public class GUINhaCungCap extends javax.swing.JFrame {
    DefaultTableModel model;
    BLLNhaCungCap BLLncc = new BLLNhaCungCap();
    /**
     * Creates new form NhaCungCapJFrame
     */
    public GUINhaCungCap() {
        initComponents();
        setLocationRelativeTo(null);
        Color col = new Color(51,51,51);
        getContentPane().setBackground(col);
        loadNCCList();
        model =(DefaultTableModel) TableNCC.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        textSearchMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textSearchTen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNCC = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        textDiaChi = new javax.swing.JTextField();
        buttonTim = new javax.swing.JButton();
        textTenNCC = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        textMaNCC = new javax.swing.JTextField();
        textSDT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhà Cung Cấp");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Địa Chỉ");

        textSearchMa.setText("Nhập mã");
        textSearchMa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSearchMaMouseClicked(evt);
            }
        });
        textSearchMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearchMaActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SĐT");

        textSearchTen.setText("Nhập tên");
        textSearchTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSearchTenMouseClicked(evt);
            }
        });

        TableNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Địa Chỉ", "SĐT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableNCC);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NHÀ CUNG CẤP");

        addButton.setBackground(new java.awt.Color(102, 102, 102));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_add_20px.png"))); // NOI18N
        addButton.setText("Thêm");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(102, 102, 102));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_maintenance_20px.png"))); // NOI18N
        updateButton.setText("Sửa");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        delButton.setBackground(new java.awt.Color(102, 102, 102));
        delButton.setForeground(new java.awt.Color(255, 255, 255));
        delButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_cancel_20px.png"))); // NOI18N
        delButton.setText("Xóa");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        buttonTim.setBackground(new java.awt.Color(102, 102, 102));
        buttonTim.setForeground(new java.awt.Color(255, 255, 255));
        buttonTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_search_20px_1.png"))); // NOI18N
        buttonTim.setText("Tìm kiếm");
        buttonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTimActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(102, 102, 102));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/backicon.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã Nhà Cung Cấp");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên Nhà Cung Cấp");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(372, 372, 372)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(textSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textDiaChi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textTenNCC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textMaNCC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textSearchTen, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textSearchMa, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(buttonTim))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cancelButton)
                .addGap(67, 497, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSearchMa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSearchTen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonTim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        GUITrangChu tc_gui = new GUITrangChu();
        tc_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void loadNCCList(){
        model = new DefaultTableModel();
        model.addColumn("Tên NCC");
        model.addColumn("Mã NCC");
        model.addColumn("Địa chỉ");
        model.addColumn("SĐT");
        TableNCC.setModel(model);
        ArrayList<DTONhaCungCap> arr = new ArrayList<DTONhaCungCap>();
        arr = BLLncc.BLLgetDL();
        for(int i = 0; i < arr.size(); i++){
            DTONhaCungCap ncc = arr.get(i);
            String mancc = ncc.getMaNCC();
            String tenncc = ncc.getTenNCC();
            String address = ncc.getDiaChi();
            String sdt = ncc.getSDT();
            Object[] row = {mancc,tenncc,address,sdt};
            model.addRow(row);
        }
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(textMaNCC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập mã nhà cung cấp!");
        }
        else if(textTenNCC.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập tên nhà cung cấp!");
        }
        else if(textDiaChi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập địa chỉ!");
        }
        else if(textSDT.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập số điện thoại nhà cung cấp!");
        }
        else{
            DTONhaCungCap ncc = new DTONhaCungCap();
            ncc.setMaNCC(textMaNCC.getText());
            ncc.setTenNCC(textTenNCC.getText());
            ncc.setDiaChi(textDiaChi.getText());
            ncc.setSDT(textSDT.getText());
            JOptionPane.showMessageDialog(this,BLLncc.BLLthem(ncc));
            loadNCCList();
            textMaNCC.setText("");
            textTenNCC.setText("");
            textDiaChi.setText("");
            textSDT.setText("");
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        int i=TableNCC.getSelectedRow();
        DTONhaCungCap ncc = new DTONhaCungCap();
        if(i>=0){ 
            ncc.setMaNCC(model.getValueAt(i, 0).toString()); 
            ncc.setTenNCC(model.getValueAt(i, 1).toString());
            ncc.setDiaChi(model.getValueAt(i, 2).toString());
            ncc.setSDT(model.getValueAt(i, 3).toString());
        }
        JOptionPane.showMessageDialog(this,BLLncc.BLLxoa(ncc));
        loadNCCList();
        textMaNCC.setText("");
        textTenNCC.setText("");
        textDiaChi.setText("");
        textSDT.setText("");
    }//GEN-LAST:event_delButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int i=TableNCC.getSelectedRow();
        DTONhaCungCap ncc = new DTONhaCungCap();
        if (i>=0){
            ncc.setMaNCC(textMaNCC.getText());
            ncc.setTenNCC(textTenNCC.getText());
            ncc.setDiaChi(textDiaChi.getText());
            ncc.setSDT(textSDT.getText());
        } 
        JOptionPane.showMessageDialog(this, BLLncc.BLLsua(ncc));
        loadNCCList();
        textMaNCC.setText("");
        textTenNCC.setText("");
        textDiaChi.setText("");
        textSDT.setText("");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void TableNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNCCMouseClicked
        // TODO add your handling code here:
        int i=TableNCC.getSelectedRow();
        if (i>=0){
            textMaNCC.setText(model.getValueAt(i, 0).toString().trim()); 
            textTenNCC.setText(model.getValueAt(i, 1).toString());
            textDiaChi.setText(model.getValueAt(i, 2).toString());
            textSDT.setText(model.getValueAt(i, 3).toString());
        }
    }//GEN-LAST:event_TableNCCMouseClicked

    private void textSearchMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearchMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchMaActionPerformed

    private void textSearchMaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSearchMaMouseClicked
        // TODO add your handling code here:
        textSearchMa.setText("");
    }//GEN-LAST:event_textSearchMaMouseClicked

    private void textSearchTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSearchTenMouseClicked
        // TODO add your handling code here:
        textSearchTen.setText("");
    }//GEN-LAST:event_textSearchTenMouseClicked

    private void buttonTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTimActionPerformed
        // TODO add your handling code here:
        DTONhaCungCap ncc = BLLncc.BLLtim(textSearchMa.getText().trim());
        if(ncc != null){
            model = new DefaultTableModel();
            model.addColumn("Mã NCC");
            model.addColumn("Tên NCC");
            model.addColumn("Địa chỉ");
            model.addColumn("SĐT");
            TableNCC.setModel(model);
            Object[] row = {ncc.getMaNCC(),ncc.getTenNCC(),ncc.getDiaChi(),ncc.getSDT()};
            model.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã nhà cung cấp");
        }
    }//GEN-LAST:event_buttonTimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadNCCList();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINhaCungCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableNCC;
    private javax.swing.JButton addButton;
    private javax.swing.JButton buttonTim;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton delButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textDiaChi;
    private javax.swing.JTextField textMaNCC;
    private javax.swing.JTextField textSDT;
    private javax.swing.JTextField textSearchMa;
    private javax.swing.JTextField textSearchTen;
    private javax.swing.JTextField textTenNCC;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
