/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BLLPhieuNhap;
import DTO.DTONhanVien;
import DTO.DTOPhieuNhap;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 3dx
 */
public class GUIPhieuNhap extends javax.swing.JFrame {
    DefaultTableModel model;
    BLLPhieuNhap BLLpn = new BLLPhieuNhap();
    /**
     * Creates new form PhieuNhapJFrame
     */
    public GUIPhieuNhap() {
        initComponents();
        setLocationRelativeTo(null);
        Color col = new Color(51,51,51);
        getContentPane().setBackground(col);
        loadPNList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDel = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textNgayNhap = new javax.swing.JTextField();
        textGioNhap = new javax.swing.JTextField();
        textMaPN = new javax.swing.JTextField();
        textMaNCC = new javax.swing.JTextField();
        textTongTien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePN = new javax.swing.JTable();
        textMaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Phiếu Nhập");
        setResizable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PHIẾU NHẬP");

        buttonAdd.setBackground(new java.awt.Color(102, 102, 102));
        buttonAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_add_20px.png"))); // NOI18N
        buttonAdd.setText("Thêm");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonUpdate.setBackground(new java.awt.Color(102, 102, 102));
        buttonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        buttonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_maintenance_20px.png"))); // NOI18N
        buttonUpdate.setText("Sửa");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDel.setBackground(new java.awt.Color(102, 102, 102));
        buttonDel.setForeground(new java.awt.Color(255, 255, 255));
        buttonDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_cancel_20px.png"))); // NOI18N
        buttonDel.setText("Xóa");
        buttonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelActionPerformed(evt);
            }
        });

        buttonSearch.setBackground(new java.awt.Color(102, 102, 102));
        buttonSearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_search_20px_1.png"))); // NOI18N
        buttonSearch.setText("Tìm kiếm");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã Nhà Cung Cấp");

        textMaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaNCCActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã Phiếu Nhập");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Giờ Nhập");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ngày Nhập");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tổng Tiền");

        tablePN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phiếu Nhập", "Giờ Nhập", "Ngày Nhập", "Tổng Tiền", "Mã Nhà Cung Cấp", "Mã Nhân Viên"
            }
        ));
        tablePN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePNMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePN);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã Nhân Viên");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/backicon.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textSearch.setText("Nhập mã phiếu nhập");
        textSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSearchMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(358, 358, 358)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(216, 216, 216))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(textTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                                .addComponent(textMaNCC)
                                                .addComponent(textGioNhap)
                                                .addComponent(textNgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                                .addComponent(textMaPN))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSearch)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textGioNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel1)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSearch)
                            .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaNCCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GUITrangChu tc_gui = new GUITrangChu();
        tc_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        try {
            if(textMaPN.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập mã phiếu nhập!");
            }
            else if(textGioNhap.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập giờ!");
            }
            else if(textNgayNhap.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập ngày!");
            }
            else if(textTongTien.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập tổng tiền!");
            }
            else if(textMaNCC.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập mã nhà cung cấp!");
            }
            else if(textMaNV.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập mã nhân viên!");
            }
            else{
                DTOPhieuNhap pn = new DTOPhieuNhap();
                pn.setMaPhieuNhap(textMaPN.getText());
                pn.setGioNhap(Integer.valueOf(textGioNhap.getText()));
                pn.setNgayNhap(textNgayNhap.getText());
                pn.setTongTien(Float.valueOf(textTongTien.getText()));
                pn.setMaNCC(textMaNCC.getText());
                pn.setMaNV(textMaNV.getText());
                JOptionPane.showMessageDialog(this,BLLpn.BLLthem(pn));
                loadPNList();
                textMaNCC.setText("");textMaPN.setText("");textMaNV.setText("");textGioNhap.setText("");textNgayNhap.setText("");textTongTien.setText("");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelActionPerformed
        // TODO add your handling code here:
        int i=tablePN.getSelectedRow();
        DTOPhieuNhap pn = new DTOPhieuNhap();
        if (i>=0){
            pn.setMaPhieuNhap(model.getValueAt(i, 0).toString()); 
            pn.setGioNhap(Integer.valueOf(model.getValueAt(i, 1).toString()));
            pn.setNgayNhap(model.getValueAt(i, 2).toString());
            pn.setTongTien(Float.valueOf(model.getValueAt(i, 3).toString()));
            pn.setMaNCC(model.getValueAt(i, 4).toString());
            pn.setMaNV(model.getValueAt(i, 4).toString());
        }
        JOptionPane.showMessageDialog(this,BLLpn.BLLxoa(pn));
        loadPNList();
        textMaNCC.setText("");textMaPN.setText("");textMaNV.setText("");textGioNhap.setText("");textNgayNhap.setText("");textTongTien.setText("");
    }//GEN-LAST:event_buttonDelActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        int i=tablePN.getSelectedRow();
        DTOPhieuNhap pn = new DTOPhieuNhap();
        if (i>=0){
            pn.setMaPhieuNhap(textMaPN.getText()); 
            pn.setGioNhap(Integer.valueOf(textGioNhap.getText()));
            pn.setNgayNhap(textNgayNhap.getText());
            pn.setTongTien(Float.valueOf(textTongTien.getText()));
            pn.setMaNCC(textMaNCC.getText());
            pn.setMaNV(textMaNV.getText());
        }  
        JOptionPane.showMessageDialog(this,BLLpn.BLLsua(pn));
        loadPNList();
        textMaNCC.setText("");textMaPN.setText("");textMaNV.setText("");textGioNhap.setText("");textNgayNhap.setText("");textTongTien.setText("");
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void tablePNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePNMouseClicked
        // TODO add your handling code here:
        int i=tablePN.getSelectedRow();
        if (i>=0){
            textMaPN.setText(model.getValueAt(i, 0).toString().trim()); 
            textGioNhap.setText(model.getValueAt(i, 1).toString());
            textNgayNhap.setText(model.getValueAt(i, 2).toString());
            textTongTien.setText(model.getValueAt(i, 3).toString());
            textMaNCC.setText(model.getValueAt(i, 4).toString());
            textMaNV.setText(model.getValueAt(i, 5).toString());

        }
    }//GEN-LAST:event_tablePNMouseClicked

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        DTOPhieuNhap pn = BLLpn.BLLtim(textSearch.getText().trim());
        if(pn != null){
            model = new DefaultTableModel();
            model.addColumn("Mã PN");
            model.addColumn("Giờ nhập");
            model.addColumn("Ngày nhập");
            model.addColumn("Tổng tiền");
            model.addColumn("Mã NCC");
            model.addColumn("Mã NV");
            tablePN.setModel(model);
            Object[] row = {pn.getMaPhieuNhap(),pn.getGioNhap(),pn.getNgayNhap(),pn.getTongTien(),pn.getMaNCC(),pn.getMaNV()};
            model.addRow(row);
        }else{
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã phiếu nhập");
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        loadPNList();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSearchMouseClicked
        // TODO add your handling code here:
        textSearch.setText("");
    }//GEN-LAST:event_textSearchMouseClicked

    
    public void loadPNList(){
        model = new DefaultTableModel();
        model.addColumn("Mã PN");
        model.addColumn("Giờ nhập");
        model.addColumn("Ngày nhập");
        model.addColumn("Tổng tiền");
        model.addColumn("Mã NCC");
        model.addColumn("Mã NV");
        tablePN.setModel(model);
        ArrayList<DTOPhieuNhap> arr = new ArrayList<DTOPhieuNhap>();
        arr = BLLpn.BLLgetDL();
        for(int i = 0; i < arr.size(); i++){
            DTOPhieuNhap pn = arr.get(i);
            String mapn = pn.getMaPhieuNhap();
            int gioNhap = pn.getGioNhap();
            String ngayNhap = pn.getNgayNhap();
            Float tongTien = pn.getTongTien();
            String mancc = pn.getMaNCC();
            String manv = pn.getMaNV();
            Object[] row = {mapn,gioNhap,ngayNhap,tongTien,mancc,manv};
            model.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDel;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePN;
    private javax.swing.JTextField textGioNhap;
    private javax.swing.JTextField textMaNCC;
    private javax.swing.JTextField textMaNV;
    private javax.swing.JTextField textMaPN;
    private javax.swing.JTextField textNgayNhap;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextField textTongTien;
    // End of variables declaration//GEN-END:variables
}
