/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BLLSanPham;
import DTO.Android;
import DTO.ChiTietSanPham;
import DTO.DTOSanPham;
import DTO.iOS;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author 3dx
 */
public class GUISanPham extends javax.swing.JFrame {
    DefaultTableModel modelIOS, modelADNROID;
    BLLSanPham BLLsp = new BLLSanPham();
    TableColumn column1;
    /**
     * Creates new form SanPhamJFrame
     */
    public GUISanPham() {
        initComponents();
        setLocationRelativeTo(null);
        Color col = new Color(51,51,51);
        getContentPane().setBackground(col);
        this.setLocationRelativeTo(null);
        loadIOSList(); loadANDROIDList();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TableSPIOS = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        delButtonANDROID = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSPANDROID = new javax.swing.JTable();
        searchButttonANDROID = new javax.swing.JButton();
        updateButtonANDROID = new javax.swing.JButton();
        textSearchTenANDROID = new javax.swing.JTextField();
        addButtonANDROID = new javax.swing.JButton();
        textSearchMaANDROID = new javax.swing.JTextField();
        buttonRSAND = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        textMaSanPhamANDROID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textTenSanPhamANDROID = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textSoLuongANDROID = new javax.swing.JTextField();
        textDonGiaANDROID = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        textNSXANDROID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textHang = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        textBaohanhAND = new javax.swing.JTextField();
        textMausacAND = new javax.swing.JTextField();
        textManhinhAND = new javax.swing.JTextField();
        textPinAND = new javax.swing.JTextField();
        textRamAND = new javax.swing.JTextField();
        textRomAND = new javax.swing.JTextField();
        textKhoiluongAND = new javax.swing.JTextField();
        textXuatxuAND = new javax.swing.JTextField();
        textThietkeAND = new javax.swing.JTextField();
        textCameraAND = new javax.swing.JTextField();
        textIMEIAND = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        updateButtonIOS = new javax.swing.JButton();
        textSearchTenIOS = new javax.swing.JTextField();
        delButtonIOS = new javax.swing.JButton();
        searchButttonIOS = new javax.swing.JButton();
        addButtonIOS = new javax.swing.JButton();
        textSearchMaIOS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSPIOS = new javax.swing.JTable();
        buttonRSIOS = new javax.swing.JButton();
        buttonXemCTSP = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        textMaSanPhamIOS = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        textTenSanPhamIOS = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        textSoLuongIOS = new javax.swing.JTextField();
        textDonGiaIOS = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        textNSXIOS = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textPhienBan = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        textBaohanhIOS = new javax.swing.JTextField();
        textMausacIOS = new javax.swing.JTextField();
        textManhinhIOS = new javax.swing.JTextField();
        textPinIOS = new javax.swing.JTextField();
        textRamIOS = new javax.swing.JTextField();
        textRomIOS = new javax.swing.JTextField();
        textKhoiluongIOS = new javax.swing.JTextField();
        textXuatxuIOS = new javax.swing.JTextField();
        textThietkeIOS = new javax.swing.JTextField();
        textCameraIOS = new javax.swing.JTextField();
        textIMEIIOS = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        jTextField6.setText("jTextField6");

        jLabel1.setText("jLabel1");

        TableSPIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Năm Sản Xuất", "Phiên bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Sản Phẩm");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SẢN PHẨM");

        cancelButton.setBackground(new java.awt.Color(85, 85, 85));
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/backicon.png"))); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));

        delButtonANDROID.setBackground(new java.awt.Color(102, 102, 102));
        delButtonANDROID.setForeground(new java.awt.Color(255, 255, 255));
        delButtonANDROID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_cancel_20px.png"))); // NOI18N
        delButtonANDROID.setText("Xóa");
        delButtonANDROID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonANDROIDActionPerformed(evt);
            }
        });

        tableSPANDROID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn Giá", "Năm Sản Xuất", "Hãng", "Hình"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSPANDROID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSPANDROIDMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableSPANDROID);

        searchButttonANDROID.setBackground(new java.awt.Color(102, 102, 102));
        searchButttonANDROID.setForeground(new java.awt.Color(255, 255, 255));
        searchButttonANDROID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_search_20px_1.png"))); // NOI18N
        searchButttonANDROID.setText("Tìm kiếm");
        searchButttonANDROID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButttonANDROIDActionPerformed(evt);
            }
        });

        updateButtonANDROID.setBackground(new java.awt.Color(102, 102, 102));
        updateButtonANDROID.setForeground(new java.awt.Color(255, 255, 255));
        updateButtonANDROID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_maintenance_20px.png"))); // NOI18N
        updateButtonANDROID.setText("Sửa");
        updateButtonANDROID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonANDROIDActionPerformed(evt);
            }
        });

        textSearchTenANDROID.setText("Nhập tên");
        textSearchTenANDROID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSearchTenANDROIDMouseClicked(evt);
            }
        });

        addButtonANDROID.setBackground(new java.awt.Color(102, 102, 102));
        addButtonANDROID.setForeground(new java.awt.Color(255, 255, 255));
        addButtonANDROID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_add_20px.png"))); // NOI18N
        addButtonANDROID.setText("Thêm");
        addButtonANDROID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonANDROIDActionPerformed(evt);
            }
        });

        textSearchMaANDROID.setText("Nhập mã");
        textSearchMaANDROID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSearchMaANDROIDMouseClicked(evt);
            }
        });

        buttonRSAND.setBackground(new java.awt.Color(102, 102, 102));
        buttonRSAND.setForeground(new java.awt.Color(255, 255, 255));
        buttonRSAND.setText("Reset");
        buttonRSAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRSANDActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xem CTSP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(60, 60, 60));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mã Sản Phẩm");

        textMaSanPhamANDROID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaSanPhamANDROIDActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tên Sản Phẩm");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Số Lượng");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Đơn Giá");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Năm Sản Xuất");

        textNSXANDROID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNSXANDROIDActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hãng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel17)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textMaSanPhamANDROID, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(textTenSanPhamANDROID, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(textSoLuongANDROID)
                    .addComponent(textDonGiaANDROID)
                    .addComponent(textNSXANDROID)
                    .addComponent(textHang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMaSanPhamANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTenSanPhamANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(textSoLuongANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(textDonGiaANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(textNSXANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("SP", jPanel3);

        jPanel4.setBackground(new java.awt.Color(60, 60, 60));

        textBaohanhAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBaohanhANDActionPerformed(evt);
            }
        });

        textMausacAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMausacANDActionPerformed(evt);
            }
        });

        textRamAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRamANDActionPerformed(evt);
            }
        });

        textRomAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRomANDActionPerformed(evt);
            }
        });

        textXuatxuAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textXuatxuANDActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bao Hanh");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mau sac");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Man hinh");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pin");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RAM");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ROM");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Thiet ke");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Camera");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Xuat xu");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Khoi luong");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("IMEI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBaohanhAND)
                    .addComponent(textManhinhAND)
                    .addComponent(textPinAND)
                    .addComponent(textRamAND, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textRomAND)
                    .addComponent(textMausacAND))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textIMEIAND, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(textThietkeAND)
                    .addComponent(textCameraAND)
                    .addComponent(textXuatxuAND)
                    .addComponent(textKhoiluongAND))
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBaohanhAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textThietkeAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCameraAND, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel23))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textMausacAND, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textManhinhAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textXuatxuAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPinAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textKhoiluongAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRamAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIMEIAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRomAND, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("CTSP", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 764, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonRSAND))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButtonANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(delButtonANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(updateButtonANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSearchMaANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSearchTenANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(searchButttonANDROID)
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRSAND, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(textSearchMaANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textSearchTenANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(searchButttonANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButtonANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delButtonANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(updateButtonANDROID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("ANDROID", jPanel1);

        jPanel2.setBackground(new java.awt.Color(60, 60, 60));

        updateButtonIOS.setBackground(new java.awt.Color(102, 102, 102));
        updateButtonIOS.setForeground(new java.awt.Color(255, 255, 255));
        updateButtonIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_maintenance_20px.png"))); // NOI18N
        updateButtonIOS.setText("Sửa");
        updateButtonIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonIOSActionPerformed(evt);
            }
        });

        textSearchTenIOS.setText("Nhập tên");
        textSearchTenIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSearchTenIOSMouseClicked(evt);
            }
        });

        delButtonIOS.setBackground(new java.awt.Color(102, 102, 102));
        delButtonIOS.setForeground(new java.awt.Color(255, 255, 255));
        delButtonIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_cancel_20px.png"))); // NOI18N
        delButtonIOS.setText("Xóa");
        delButtonIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonIOSActionPerformed(evt);
            }
        });

        searchButttonIOS.setBackground(new java.awt.Color(102, 102, 102));
        searchButttonIOS.setForeground(new java.awt.Color(255, 255, 255));
        searchButttonIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_search_20px_1.png"))); // NOI18N
        searchButttonIOS.setText("Tìm kiếm");
        searchButttonIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButttonIOSActionPerformed(evt);
            }
        });

        addButtonIOS.setBackground(new java.awt.Color(102, 102, 102));
        addButtonIOS.setForeground(new java.awt.Color(255, 255, 255));
        addButtonIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_add_20px.png"))); // NOI18N
        addButtonIOS.setText("Thêm");
        addButtonIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonIOSActionPerformed(evt);
            }
        });

        textSearchMaIOS.setText("Nhập mã");
        textSearchMaIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSearchMaIOSMouseClicked(evt);
            }
        });

        tableSPIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Năm sản xuất", "Phiên bản", "Hình"
            }
        ));
        tableSPIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSPIOSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSPIOS);

        buttonRSIOS.setBackground(new java.awt.Color(102, 102, 102));
        buttonRSIOS.setForeground(new java.awt.Color(255, 255, 255));
        buttonRSIOS.setText("Reset");
        buttonRSIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRSIOSActionPerformed(evt);
            }
        });

        buttonXemCTSP.setBackground(new java.awt.Color(102, 102, 102));
        buttonXemCTSP.setForeground(new java.awt.Color(255, 255, 255));
        buttonXemCTSP.setText("Xem CTSP");
        buttonXemCTSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXemCTSPActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(60, 60, 60));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Mã Sản Phẩm");

        textMaSanPhamIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMaSanPhamIOSActionPerformed(evt);
            }
        });

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Tên Sản Phẩm");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Số Lượng");

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Đơn Giá");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Năm Sản Xuất");

        textNSXIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNSXIOSActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Phiên bản");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textMaSanPhamIOS, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(textTenSanPhamIOS, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(textSoLuongIOS)
                    .addComponent(textDonGiaIOS)
                    .addComponent(textNSXIOS)
                    .addComponent(textPhienBan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMaSanPhamIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTenSanPhamIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(textSoLuongIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(textDonGiaIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(textNSXIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(textPhienBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("SP", jPanel5);

        jPanel6.setBackground(new java.awt.Color(60, 60, 60));

        textBaohanhIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBaohanhIOSActionPerformed(evt);
            }
        });

        textMausacIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMausacIOSActionPerformed(evt);
            }
        });

        textRamIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRamIOSActionPerformed(evt);
            }
        });

        textRomIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRomIOSActionPerformed(evt);
            }
        });

        textXuatxuIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textXuatxuIOSActionPerformed(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Bao Hanh");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Mau sac");

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Man hinh");

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Pin");

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("RAM");

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("ROM");

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Thiet ke");

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Camera");

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Xuat xu");

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Khoi luong");

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("IMEI");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel32)
                        .addComponent(jLabel34)
                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel37)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBaohanhIOS)
                    .addComponent(textManhinhIOS)
                    .addComponent(textPinIOS)
                    .addComponent(textRamIOS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textRomIOS)
                    .addComponent(textMausacIOS))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel41)
                        .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel39)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textIMEIIOS, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(textThietkeIOS)
                    .addComponent(textCameraIOS)
                    .addComponent(textXuatxuIOS)
                    .addComponent(textKhoiluongIOS))
                .addGap(33, 33, 33))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBaohanhIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textThietkeIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textCameraIOS, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel39))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textMausacIOS, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addComponent(jLabel33)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textManhinhIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textXuatxuIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPinIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textKhoiluongIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRamIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textIMEIIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRomIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("CTSP", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(updateButtonIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(addButtonIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(delButtonIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textSearchMaIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textSearchTenIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(searchButttonIOS)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonXemCTSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRSIOS)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRSIOS)
                    .addComponent(buttonXemCTSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(textSearchMaIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textSearchTenIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(searchButttonIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(delButtonIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addButtonIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(updateButtonIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("IOS", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelButton)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        GUITrangChu tc_gui = new GUITrangChu();
        tc_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
  
    private void updateButtonIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonIOSActionPerformed
        // TODO add your handling code here:
        int i=tableSPIOS.getSelectedRow();
        iOS sp = new iOS();
        if (i>=0){
            sp.setMaSanPham(textMaSanPhamIOS.getText()); 
            sp.setTenSanPham(textTenSanPhamIOS.getText());
            sp.setSoLuong(Integer.valueOf(textSoLuongIOS.getText()));
            sp.setDonGia(Float.valueOf(textDonGiaIOS.getText()));
            sp.setNamSX(Integer.valueOf(textNSXIOS.getText()));
            sp.setPhienbanios(Float.valueOf(textPhienBan.getText()));
        }  
        JOptionPane.showMessageDialog(this,BLLsp.BLLsuaIOS(sp));
        loadIOSList();
        textMaSanPhamIOS.setText("");
        textTenSanPhamIOS.setText("");
        textSoLuongIOS.setText("");
        textDonGiaIOS.setText("");
        textNSXIOS.setText("");
        textPhienBan.setText("");
    }//GEN-LAST:event_updateButtonIOSActionPerformed

    private void textSearchTenIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSearchTenIOSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchTenIOSMouseClicked

    private void delButtonIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonIOSActionPerformed
        // TODO add your handling code here:
        int i=tableSPIOS.getSelectedRow();
        iOS sp = new iOS();
        if (i>=0){
            sp.setMaSanPham(modelIOS.getValueAt(i, 0).toString()); 
            sp.setTenSanPham(modelIOS.getValueAt(i, 1).toString());
            sp.setSoLuong(Integer.valueOf(modelIOS.getValueAt(i, 2).toString()));
            sp.setDonGia(Float.valueOf(modelIOS.getValueAt(i, 3).toString()));
            sp.setNamSX(Integer.valueOf(modelIOS.getValueAt(i, 4).toString()));
            sp.setPhienbanios(Float.valueOf(modelIOS.getValueAt(i, 5).toString()));
        }
        JOptionPane.showMessageDialog(this,BLLsp.BLLxoaIOS(sp));
        loadIOSList();
        textMaSanPhamIOS.setText("");
        textTenSanPhamIOS.setText("");
        textSoLuongIOS.setText("");
        textDonGiaIOS.setText("");
        textNSXIOS.setText("");
        textPhienBan.setText("");        
    }//GEN-LAST:event_delButtonIOSActionPerformed

    private void searchButttonIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButttonIOSActionPerformed
        // TODO add your handling code here:
        iOS sp = BLLsp.BLLtimIOS(textSearchMaIOS.getText().trim());
        if(sp != null){
            modelIOS = new DefaultTableModel();
            modelIOS.addColumn("Mã sản phẩm");
            modelIOS.addColumn("Tên sản phẩm");
            modelIOS.addColumn("Số lượng ");
            modelIOS.addColumn("Đơn giá");
            modelIOS.addColumn("Năm sản xuất");
            modelIOS.addColumn("Phiên bản");
            tableSPIOS.setModel(modelIOS);
            Object[] row = {sp.getMaSanPham(),sp.getTenSanPham(),sp.getSoLuong(),sp.getDonGia(),sp.getNamSX(),sp.getPhienbanios()};
            modelIOS.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã sản phẩm");
        }
    }//GEN-LAST:event_searchButttonIOSActionPerformed

    public void loadIOSList(){
        modelIOS = new DefaultTableModel();
        modelIOS.addColumn("Mã SP");
        modelIOS.addColumn("Tên sản phẩm");
        modelIOS.addColumn("Số lượng");
        modelIOS.addColumn("Đơn giá");
        modelIOS.addColumn("Năm SX");
        modelIOS.addColumn("Phiên bản");
        modelIOS.addColumn("Img");
        tableSPIOS.setModel(modelIOS);
        column1 = tableSPIOS.getColumnModel().getColumn(1);
        column1.setPreferredWidth(150);
        ArrayList<DTOSanPham> arr = new ArrayList<DTOSanPham>();
        arr = BLLsp.BLLgetIOS();
        for(int i = 0; i < arr.size(); i++){
            DTOSanPham sp = arr.get(i);
            if(sp instanceof iOS){
                iOS ios = (iOS) sp;
                String masp = ios.getMaSanPham();
                String tensp = ios.getTenSanPham();
                Integer sl = ios.getSoLuong();
                Float dongia = ios.getDonGia();
                Integer nsx = ios.getNamSX();
                Float pb = ios.getPhienbanios();
                String img = ios.getImg();
                Object[] row = {masp,tensp,sl,dongia,nsx,pb,img};
                modelIOS.addRow(row);
            }
        }
    }
    
    public void loadANDROIDList(){
        modelADNROID = new DefaultTableModel();
        modelADNROID.addColumn("Mã SP");
        modelADNROID.addColumn("Tên sản phẩm");
        modelADNROID.addColumn("Số lượng");
        modelADNROID.addColumn("Đơn giá");
        modelADNROID.addColumn("Năm SX");
        modelADNROID.addColumn("Hãng");
        modelADNROID.addColumn("Img");
        tableSPANDROID.setModel(modelADNROID);
        column1 = tableSPANDROID.getColumnModel().getColumn(1);
        column1.setPreferredWidth(200);
        ArrayList<DTOSanPham> arr = new ArrayList<DTOSanPham>();
        arr = BLLsp.BLLgetANDROID();
        for(int i = 0; i < arr.size(); i++){
            DTOSanPham sp = arr.get(i);
            if(sp instanceof Android){
                Android and = (Android) sp;
                String masp = and.getMaSanPham();
                String tensp = and.getTenSanPham();
                Integer sl = and.getSoLuong();
                Float dongia = and.getDonGia();
                Integer nsx = and.getNamSX();
                String hang = and.getHangSanXuat();
                String img = and.getImg();
                Object[] row = {masp,tensp,sl,dongia,nsx,hang,img};
                modelADNROID.addRow(row);
            }
        }
    }
    
    private void addButtonIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonIOSActionPerformed
        // TODO add your handling code here:
        try {
            if(textMaSanPhamIOS.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập mã sản phẩm!");
            }
            else if(textTenSanPhamIOS.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập tên sản phẩm!");
            }
            else if(textSoLuongIOS.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập số lượng!");
            }
            else if(textDonGiaIOS.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập đơn giá!");
            }
            else if(textNSXIOS.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập nhà sản xuất!");
            }
            else if(textPhienBan.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập phiên bản!");
            }
            else{
                iOS ios = new iOS();
                ios.setMaSanPham(textMaSanPhamIOS.getText());
                ios.setTenSanPham(textTenSanPhamIOS.getText());
                ios.setSoLuong(Integer.valueOf(textSoLuongIOS.getText()));
                ios.setDonGia(Float.valueOf(textDonGiaIOS.getText()));
                ios.setNamSX(Integer.valueOf(textNSXIOS.getText()));
                ios.setPhienbanios(Float.valueOf(textPhienBan.getText()));
                ios.setImg(null);
                JOptionPane.showMessageDialog(this,BLLsp.BLLthemIOS(ios));
                loadIOSList();
                textMaSanPhamIOS.setText("");
                textTenSanPhamIOS.setText("");
                textSoLuongIOS.setText("");
                textDonGiaIOS.setText("");
                textNSXIOS.setText("");
                textPhienBan.setText("");
//                ChiTietSanPham ctspios = new ChiTietSanPham();
//                ctspios.setMaSP(textMaSanPhamIOS.getText());
//                ctspios.setBaoHanh(textBaohanhIOS.getText());
//                ctspios.setMauSac(textMausacIOS.getText());
//                ctspios.setIMEI(textIMEIIOS.getText());
//                ctspios.setManHinh(textManhinhIOS.getText());
//                ctspios.setRam(textRamIOS.getText());
//                ctspios.setRom(textRomIOS.getText());
//                ctspios.setPin(textPinIOS.getText());
//                ctspios.setThietKe(textThietkeIOS.getText());
//                ctspios.setCamera(textCameraIOS.getText());
//                ctspios.setXuatXu(textXuatxuIOS.getText());
//                ctspios.setKhoiLuong(Float.valueOf(textKhoiluongIOS.getText()));
//                BLLsp.BLLthemct(ctspios);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_addButtonIOSActionPerformed

    private void textSearchMaIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSearchMaIOSMouseClicked
        // TODO add your handling code here:
        textSearchMaIOS.setText("");
    }//GEN-LAST:event_textSearchMaIOSMouseClicked

    private void delButtonANDROIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonANDROIDActionPerformed
        // TODO add your handling code here:
        int i=tableSPANDROID.getSelectedRow();
        Android sp = new Android();
        if (i>=0){
            sp.setMaSanPham(modelADNROID.getValueAt(i, 0).toString()); 
            sp.setTenSanPham(modelADNROID.getValueAt(i, 1).toString());
            sp.setSoLuong(Integer.valueOf(modelADNROID.getValueAt(i, 2).toString()));
            sp.setDonGia(Float.valueOf(modelADNROID.getValueAt(i, 3).toString()));
            sp.setNamSX(Integer.valueOf(modelADNROID.getValueAt(i, 4).toString()));
            sp.setHangSanXuat(modelADNROID.getValueAt(i, 5).toString());
        }
        JOptionPane.showMessageDialog(this,BLLsp.BLLxoaANDROID(sp));
        loadANDROIDList();
    }//GEN-LAST:event_delButtonANDROIDActionPerformed

    private void tableSPANDROIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSPANDROIDMouseClicked
        // TODO add your handling code here:
        int i=tableSPANDROID.getSelectedRow();
        if (i>=0){
            textMaSanPhamANDROID.setText(modelADNROID.getValueAt(i, 0).toString()); 
            textTenSanPhamANDROID.setText(modelADNROID.getValueAt(i, 1).toString());
            textSoLuongANDROID.setText(modelADNROID.getValueAt(i, 2).toString());
            textDonGiaANDROID.setText(modelADNROID.getValueAt(i, 3).toString());
            textNSXANDROID.setText(modelADNROID.getValueAt(i, 4).toString());
            textHang.setText(modelADNROID.getValueAt(i, 5).toString());
        }
    }//GEN-LAST:event_tableSPANDROIDMouseClicked

    private void searchButttonANDROIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButttonANDROIDActionPerformed
        // TODO add your handling code here:
        Android sp = BLLsp.BLLtimANDROID(textSearchMaANDROID.getText().trim());
        if(sp != null){
            modelADNROID = new DefaultTableModel();
            modelADNROID.addColumn("Mã sản phẩm");
            modelADNROID.addColumn("Tên sản phẩm");
            modelADNROID.addColumn("Số lượng ");
            modelADNROID.addColumn("Đơn giá");
            modelADNROID.addColumn("Năm sản xuất");
            modelADNROID.addColumn("Hãng");
            tableSPANDROID.setModel(modelADNROID);
            Object[] row = {sp.getMaSanPham(),sp.getTenSanPham(),sp.getSoLuong(),sp.getDonGia(),sp.getNamSX(),sp.getHangSanXuat()};
            modelADNROID.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã sản phẩm");
        }
    }//GEN-LAST:event_searchButttonANDROIDActionPerformed

    private void updateButtonANDROIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonANDROIDActionPerformed
        // TODO add your handling code here:
        int i=tableSPANDROID.getSelectedRow();
        Android sp = new Android();
        if (i>=0){
            sp.setMaSanPham(textMaSanPhamANDROID.getText()); 
            sp.setTenSanPham(textTenSanPhamANDROID.getText());
            sp.setSoLuong(Integer.valueOf(textSoLuongANDROID.getText()));
            sp.setDonGia(Float.valueOf(textDonGiaANDROID.getText()));
            sp.setNamSX(Integer.valueOf(textNSXANDROID.getText()));
            sp.setHangSanXuat(textHang.getText());
        }  
        JOptionPane.showMessageDialog(this,BLLsp.BLLsuaANDROID(sp));
        loadANDROIDList();
    }//GEN-LAST:event_updateButtonANDROIDActionPerformed

    private void textSearchTenANDROIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSearchTenANDROIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchTenANDROIDMouseClicked

    private void addButtonANDROIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonANDROIDActionPerformed
        // TODO add your handling code here:
        try {
            if(textMaSanPhamANDROID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Mời bạn nhập mã sản phẩm!");
            }
            else if(textTenSanPhamANDROID.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập tên sản phẩm!");
            }
            else if(textSoLuongANDROID.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập số lượng!");
            }
            else if(textDonGiaANDROID.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập đơn giá!");
            }
            else if(textNSXANDROID.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập nhà sản xuất!");
            }
            else if(textHang.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Mời bạn nhập phiên bản!");
            }
//            else if (textBaohanhAND.getText().isEmpty() || textMausacAND.getText().isEmpty() ||textManhinhAND.getText().isEmpty() ||textPinAND.getText().isEmpty() || textRamAND.getText().isEmpty()|| textRomAND.getText().isEmpty()||textThietkeAND.getText().isEmpty() || textCameraAND.getText().isEmpty()|| textXuatxuAND.getText().isEmpty() ||textKhoiluongAND.getText().isEmpty() || textIMEIAND.getText().isEmpty()){
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ chi tiết sản phẩm");
//            }     
            else{
                Android and = new Android();
                and.setMaSanPham(textMaSanPhamANDROID.getText());
                and.setTenSanPham(textTenSanPhamANDROID.getText());
                and.setSoLuong(Integer.valueOf(textSoLuongANDROID.getText()));
                and.setDonGia(Float.valueOf(textDonGiaANDROID.getText()));
                and.setNamSX(Integer.valueOf(textNSXANDROID.getText()));
                and.setHangSanXuat(textHang.getText());
                and.setImg(null);
                JOptionPane.showMessageDialog(this,BLLsp.BLLthemAndriod(and));
                loadANDROIDList();
                textMaSanPhamANDROID.setText("");
                textTenSanPhamANDROID.setText("");
                textSoLuongANDROID.setText("");
                textDonGiaANDROID.setText("");
                textNSXANDROID.setText("");
                textHang.setText("");
//                ChiTietSanPham ctspand = new ChiTietSanPham();
//                ctspand.setMaSP(textMaSanPhamANDROID.getText());
//                ctspand.setBaoHanh(textBaohanhAND.getText());
//                ctspand.setMauSac(textMausacAND.getText());
//                ctspand.setIMEI(textIMEIAND.getText());
//                ctspand.setManHinh(textManhinhAND.getText());
//                ctspand.setRam(textRamAND.getText());
//                ctspand.setRom(textRomAND.getText());
//                ctspand.setPin(textPinAND.getText());
//                ctspand.setThietKe(textThietkeAND.getText());
//                ctspand.setCamera(textCameraAND.getText());
//                ctspand.setXuatXu(textXuatxuAND.getText());
//                ctspand.setKhoiLuong(Float.valueOf(textKhoiluongAND.getText()));
//                BLLsp.BLLthemct(ctspand);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_addButtonANDROIDActionPerformed

    private void textSearchMaANDROIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSearchMaANDROIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchMaANDROIDMouseClicked

    private void tableSPIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSPIOSMouseClicked
        // TODO add your handling code here:
        int i=tableSPIOS.getSelectedRow();
        if (i>=0){
            textMaSanPhamIOS.setText(modelIOS.getValueAt(i, 0).toString().trim()); 
            textTenSanPhamIOS.setText(modelIOS.getValueAt(i, 1).toString());
            textSoLuongIOS.setText(modelIOS.getValueAt(i, 2).toString());
            textDonGiaIOS.setText(modelIOS.getValueAt(i, 3).toString());
            textNSXIOS.setText(modelIOS.getValueAt(i, 4).toString());
            textPhienBan.setText(modelIOS.getValueAt(i, 5).toString());
        }
    }//GEN-LAST:event_tableSPIOSMouseClicked

    private void buttonRSIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRSIOSActionPerformed
        // TODO add your handling code here:
        loadIOSList();
    }//GEN-LAST:event_buttonRSIOSActionPerformed

    private void buttonRSANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRSANDActionPerformed
        // TODO add your handling code here:
        loadANDROIDList();
    }//GEN-LAST:event_buttonRSANDActionPerformed

    private void buttonXemCTSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXemCTSPActionPerformed
        // TODO add your handling code here:
        int i=tableSPIOS.getSelectedRow();
        if(i>=0){
            ChiTietSanPham ctsp = BLLsp.BLLtimctspIOS(modelIOS.getValueAt(i, 0).toString());
            if(ctsp != null){
                GUIChiTietSanPham gui_ctsp = new GUIChiTietSanPham(ctsp.getMaSP(), ctsp.getBaoHanh(), ctsp.getMauSac(), ctsp.getIMEI(), ctsp.getManHinh(), ctsp.getRam(), ctsp.getRom(), ctsp.getPin(), ctsp.getThietKe(), ctsp.getCamera(), ctsp.getXuatXu(), ctsp.getKhoiLuong(),modelIOS.getValueAt(i, 1).toString(),modelIOS.getValueAt(i, 6).toString());
                gui_ctsp.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }
    }//GEN-LAST:event_buttonXemCTSPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i=tableSPANDROID.getSelectedRow();
        if(i>=0){
            ChiTietSanPham ctsp = BLLsp.BLLtimctspANDROID(tableSPANDROID.getValueAt(i, 0).toString());
            if(ctsp != null){
                GUIChiTietSanPham gui_ctsp = new GUIChiTietSanPham(ctsp.getMaSP(), ctsp.getBaoHanh(), ctsp.getMauSac(), ctsp.getIMEI(), ctsp.getManHinh(), ctsp.getRam(), ctsp.getRom(), ctsp.getPin(), ctsp.getThietKe(), ctsp.getCamera(), ctsp.getXuatXu(), ctsp.getKhoiLuong(),modelADNROID.getValueAt(i, 1).toString(),modelADNROID.getValueAt(i, 6).toString());
                gui_ctsp.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Lỗi");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textMaSanPhamANDROIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaSanPhamANDROIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaSanPhamANDROIDActionPerformed

    private void textNSXANDROIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNSXANDROIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNSXANDROIDActionPerformed

    private void textMausacANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMausacANDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMausacANDActionPerformed

    private void textXuatxuANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textXuatxuANDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textXuatxuANDActionPerformed

    private void textRamANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRamANDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRamANDActionPerformed

    private void textBaohanhANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBaohanhANDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBaohanhANDActionPerformed

    private void textRomANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRomANDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRomANDActionPerformed

    private void textMaSanPhamIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMaSanPhamIOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMaSanPhamIOSActionPerformed

    private void textNSXIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNSXIOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNSXIOSActionPerformed

    private void textBaohanhIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBaohanhIOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBaohanhIOSActionPerformed

    private void textMausacIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMausacIOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMausacIOSActionPerformed

    private void textRamIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRamIOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRamIOSActionPerformed

    private void textRomIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRomIOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRomIOSActionPerformed

    private void textXuatxuIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textXuatxuIOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textXuatxuIOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSPIOS;
    private javax.swing.JButton addButtonANDROID;
    private javax.swing.JButton addButtonIOS;
    private javax.swing.JButton buttonRSAND;
    private javax.swing.JButton buttonRSIOS;
    private javax.swing.JButton buttonXemCTSP;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton delButtonANDROID;
    private javax.swing.JButton delButtonIOS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton searchButttonANDROID;
    private javax.swing.JButton searchButttonIOS;
    private javax.swing.JTable tableSPANDROID;
    private javax.swing.JTable tableSPIOS;
    private javax.swing.JTextField textBaohanhAND;
    private javax.swing.JTextField textBaohanhIOS;
    private javax.swing.JTextField textCameraAND;
    private javax.swing.JTextField textCameraIOS;
    private javax.swing.JTextField textDonGiaANDROID;
    private javax.swing.JTextField textDonGiaIOS;
    private javax.swing.JTextField textHang;
    private javax.swing.JTextField textIMEIAND;
    private javax.swing.JTextField textIMEIIOS;
    private javax.swing.JTextField textKhoiluongAND;
    private javax.swing.JTextField textKhoiluongIOS;
    private javax.swing.JTextField textMaSanPhamANDROID;
    private javax.swing.JTextField textMaSanPhamIOS;
    private javax.swing.JTextField textManhinhAND;
    private javax.swing.JTextField textManhinhIOS;
    private javax.swing.JTextField textMausacAND;
    private javax.swing.JTextField textMausacIOS;
    private javax.swing.JTextField textNSXANDROID;
    private javax.swing.JTextField textNSXIOS;
    private javax.swing.JTextField textPhienBan;
    private javax.swing.JTextField textPinAND;
    private javax.swing.JTextField textPinIOS;
    private javax.swing.JTextField textRamAND;
    private javax.swing.JTextField textRamIOS;
    private javax.swing.JTextField textRomAND;
    private javax.swing.JTextField textRomIOS;
    private javax.swing.JTextField textSearchMaANDROID;
    private javax.swing.JTextField textSearchMaIOS;
    private javax.swing.JTextField textSearchTenANDROID;
    private javax.swing.JTextField textSearchTenIOS;
    private javax.swing.JTextField textSoLuongANDROID;
    private javax.swing.JTextField textSoLuongIOS;
    private javax.swing.JTextField textTenSanPhamANDROID;
    private javax.swing.JTextField textTenSanPhamIOS;
    private javax.swing.JTextField textThietkeAND;
    private javax.swing.JTextField textThietkeIOS;
    private javax.swing.JTextField textXuatxuAND;
    private javax.swing.JTextField textXuatxuIOS;
    private javax.swing.JButton updateButtonANDROID;
    private javax.swing.JButton updateButtonIOS;
    // End of variables declaration//GEN-END:variables
}
