package GUI;
import BLL.BLLKhachHang;
import BLL.BLLSanPham;
import DTO.Android;
import DTO.DTOKhachHang;
import java.awt.Color;
import DTO.DTOSanPham;
import DTO.iOS;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 3dx
 */
public class GUITrangChu extends javax.swing.JFrame {
    public static ArrayList<DTOSanPham> list = new ArrayList<DTOSanPham>();
    BLLSanPham BLLsp = new BLLSanPham();
    BLLKhachHang BLLkh = new BLLKhachHang();
    TableColumn column1;
    DefaultTableModel modelIOS, modelADNROID,modelGioHang;
    /**
     * Creates new form JFrameDAD
     */
    public GUITrangChu() {
        initComponents();
        setLocationRelativeTo(null);
        Color col = new Color(17,17,17);
        getContentPane().setBackground(col);
        loadIOSList();
        loadANDROIDList();
        tableIOS.setRowSelectionInterval(0, 0);
        String fileimg = (String) modelIOS.getValueAt(0, 6).toString().trim();
        ImageIcon imageIcon = new ImageIcon(fileimg);
        Image scaledImage = imageIcon.getImage().getScaledInstance(labelIMG.getWidth(), labelIMG.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        labelIMG.setIcon(scaledImageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollBar1 = new javax.swing.JScrollBar();
        logoutButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        textSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonAdd = new javax.swing.JButton();
        buttonThanhToan = new javax.swing.JButton();
        buttonBoHang = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGioHang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableIOS = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableANDROID = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelHinhAnh = new javax.swing.JPanel();
        labelIMG = new javax.swing.JLabel();
        panelKhachHang = new javax.swing.JPanel();
        textMaKH = new javax.swing.JTextField();
        textTenKH = new javax.swing.JTextField();
        textDiaChi = new javax.swing.JTextField();
        textSDT = new javax.swing.JTextField();
        conboboxGender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buttonSearchMaKH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        buttonSP = new javax.swing.JButton();
        buttonNV = new javax.swing.JButton();
        buttonPN = new javax.swing.JButton();
        buttonKH = new javax.swing.JButton();
        buttonHD = new javax.swing.JButton();
        buttonNCC = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton10.setText("jButton10");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cửa Hàng Điện Thoại\n");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        logoutButton.setBackground(new java.awt.Color(85, 85, 85));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/log-out-icon.png"))); // NOI18N
        logoutButton.setText("ĐĂNG XUẤT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        textSearch.setBackground(new java.awt.Color(242, 242, 242));
        textSearch.setText("Nhập mã sản phẩm muốn tìm");
        textSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textSearchMouseClicked(evt);
            }
        });
        textSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearchActionPerformed(evt);
            }
        });

        buttonSearch.setBackground(new java.awt.Color(102, 102, 102));
        buttonSearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch.setText("Tìm kiếm");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SẢN PHẨM");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        buttonAdd.setBackground(new java.awt.Color(102, 102, 102));
        buttonAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_add_20px.png"))); // NOI18N
        buttonAdd.setText("Thêm vào giỏ");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonThanhToan.setBackground(new java.awt.Color(102, 102, 102));
        buttonThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        buttonThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/shoppingicon.png"))); // NOI18N
        buttonThanhToan.setText("Thanh Toán");
        buttonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThanhToanActionPerformed(evt);
            }
        });

        buttonBoHang.setBackground(new java.awt.Color(102, 102, 102));
        buttonBoHang.setForeground(new java.awt.Color(255, 255, 255));
        buttonBoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_cancel_20px.png"))); // NOI18N
        buttonBoHang.setText("Bỏ");
        buttonBoHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBoHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBoHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBoHang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tableGioHang.setBackground(new java.awt.Color(242, 242, 242));
        tableGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên Sản Phẩm", "Số lượng", "Đơn Giá", "Năm Sản Xuất", "Chi tiết khác"
            }
        ));
        jScrollPane2.setViewportView(tableGioHang);
        if (tableGioHang.getColumnModel().getColumnCount() > 0) {
            tableGioHang.getColumnModel().getColumn(0).setMaxWidth(65);
            tableGioHang.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GIỎ HÀNG");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tableIOS.setBackground(new java.awt.Color(242, 242, 242));
        tableIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên Sản Phẩm", "Số lượng", "Đơn Giá", "Năm SX", "Phiên bản", "Img"
            }
        ));
        tableIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableIOSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableIOS);
        if (tableIOS.getColumnModel().getColumnCount() > 0) {
            tableIOS.getColumnModel().getColumn(0).setMaxWidth(65);
            tableIOS.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        jScrollPane5.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("IOS", jPanel6);

        tableANDROID.setBackground(new java.awt.Color(242, 242, 242));
        tableANDROID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên Sản Phẩm", "Số lượng", "Đơn Giá", "Năm SX", "Hãng", "Img"
            }
        ));
        tableANDROID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableANDROIDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableANDROID);
        if (tableANDROID.getColumnModel().getColumnCount() > 0) {
            tableANDROID.getColumnModel().getColumn(0).setMaxWidth(65);
            tableANDROID.getColumnModel().getColumn(1).setPreferredWidth(150);
        }

        jScrollPane6.setViewportView(jScrollPane3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ANDROID", jPanel7);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelHinhAnh.setMaximumSize(new java.awt.Dimension(336, 346));
        panelHinhAnh.setMinimumSize(new java.awt.Dimension(336, 346));

        labelIMG.setText("    ");

        javax.swing.GroupLayout panelHinhAnhLayout = new javax.swing.GroupLayout(panelHinhAnh);
        panelHinhAnh.setLayout(panelHinhAnhLayout);
        panelHinhAnhLayout.setHorizontalGroup(
            panelHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIMG, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );
        panelHinhAnhLayout.setVerticalGroup(
            panelHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIMG, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Hình ảnh", panelHinhAnh);

        conboboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel9.setText("Mã");

        jLabel10.setText("Tên");

        jLabel11.setText("Địa chỉ");

        jLabel12.setText("SĐT");

        jLabel13.setText("Giới tính");

        buttonSearchMaKH.setText("Tìm");
        buttonSearchMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchMaKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKhachHangLayout = new javax.swing.GroupLayout(panelKhachHang);
        panelKhachHang.setLayout(panelKhachHangLayout);
        panelKhachHangLayout.setHorizontalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(26, 26, 26)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(conboboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textMaKH)
                    .addComponent(textTenKH)
                    .addComponent(textSDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSearchMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKhachHangLayout.setVerticalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(buttonSearchMaKH))
                .addGap(18, 18, 18)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conboboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(86, 86, 86))
        );

        jTabbedPane2.addTab("Nhập khách hàng", panelKhachHang);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTabbedPane2))))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANG CHỦ");

        jPanel5.setBackground(new java.awt.Color(34, 34, 34));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Mục", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setName(""); // NOI18N

        buttonSP.setBackground(new java.awt.Color(85, 85, 85));
        buttonSP.setForeground(new java.awt.Color(255, 255, 255));
        buttonSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/spicon.png"))); // NOI18N
        buttonSP.setText("SẢN PHẨM");
        buttonSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSPActionPerformed(evt);
            }
        });

        buttonNV.setBackground(new java.awt.Color(85, 85, 85));
        buttonNV.setForeground(new java.awt.Color(255, 255, 255));
        buttonNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/stafficon.png"))); // NOI18N
        buttonNV.setText("NHÂN VIÊN");
        buttonNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNVActionPerformed(evt);
            }
        });

        buttonPN.setBackground(new java.awt.Color(85, 85, 85));
        buttonPN.setForeground(new java.awt.Color(255, 255, 255));
        buttonPN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bill-icon.png"))); // NOI18N
        buttonPN.setText("PHIẾU NHẬP");
        buttonPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPNActionPerformed(evt);
            }
        });

        buttonKH.setBackground(new java.awt.Color(85, 85, 85));
        buttonKH.setForeground(new java.awt.Color(255, 255, 255));
        buttonKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/customericon.png"))); // NOI18N
        buttonKH.setText("KHÁCH HÀNG");
        buttonKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKHActionPerformed(evt);
            }
        });

        buttonHD.setBackground(new java.awt.Color(85, 85, 85));
        buttonHD.setForeground(new java.awt.Color(255, 255, 255));
        buttonHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/billicon.png"))); // NOI18N
        buttonHD.setText("HÓA ĐƠN");
        buttonHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHDActionPerformed(evt);
            }
        });

        buttonNCC.setBackground(new java.awt.Color(85, 85, 85));
        buttonNCC.setForeground(new java.awt.Color(255, 255, 255));
        buttonNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/suppliericon.png"))); // NOI18N
        buttonNCC.setText("NHÀ CUNG CẤP");
        buttonNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(buttonSP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonHD, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonKH, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(498, 498, 498))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            GUIDangNhap dn_gui = new GUIDangNhap();
            dn_gui.setVisible(true);
            setVisible(false);
        } else{} 
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void buttonSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSPActionPerformed
        // TODO add your handling code here:
        GUISanPham sp_gui = new GUISanPham();
        sp_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonSPActionPerformed

    private void buttonPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPNActionPerformed
        // TODO add your handling code here:
        GUIPhieuNhap pn_gui = new GUIPhieuNhap();
        pn_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonPNActionPerformed

    private void buttonNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNVActionPerformed
        // TODO add your handling code here:
        GUINhanVien nv_gui = new GUINhanVien();
        nv_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonNVActionPerformed

    private void buttonHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHDActionPerformed
        // TODO add your handling code here:
        GUIHoaDon hd_gui = new GUIHoaDon();
        hd_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonHDActionPerformed

    private void buttonKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKHActionPerformed
        // TODO add your handling code here:
        GUIKhachHang kh_gui = new GUIKhachHang();
        kh_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonKHActionPerformed

    private void buttonNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNCCActionPerformed
        // TODO add your handling code here:
        GUINhaCungCap ncc_gui = new GUINhaCungCap();
        ncc_gui.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buttonNCCActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        modelIOS = (DefaultTableModel) tableIOS.getModel();
        modelADNROID = (DefaultTableModel) tableANDROID.getModel();
        int i=tableIOS.getSelectedRow();
        int j=tableANDROID.getSelectedRow();
        if (i>=0){
            iOS sp = new iOS();
            sp.setMaSanPham( modelIOS.getValueAt(i, 0).toString());
            sp.setTenSanPham(modelIOS.getValueAt(i, 1).toString());
            sp.setDonGia(Float.valueOf(modelIOS.getValueAt(i, 3).toString()));
            sp.setNamSX(Integer.valueOf(modelIOS.getValueAt(i, 4).toString()));
            sp.setPhienbanios(Float.valueOf(modelIOS.getValueAt(i, 5).toString()));
            String sl = JOptionPane.showInputDialog("Nhập số lượng");
            String tonkho = modelIOS.getValueAt(i, 2).toString();
            sp.setSoLuong(Integer.valueOf(sl));
            int newSL = Integer.valueOf(tonkho) - Integer.valueOf(sl);
            if(newSL < 0){
                JOptionPane.showMessageDialog(null, "Quá số lượng tồn kho! Mời bạn nhập lại số lượng");
            }else{
            modelGioHang = (DefaultTableModel) tableGioHang.getModel();
            modelGioHang.addRow(new Object[]{sp.getMaSanPham(), sp.getTenSanPham(), sl, sp.getDonGia(), sp.getNamSX(),sp.getPhienbanios()});
            list.add(sp);
            BLLsp.BLLsuaSLIOS(sp,newSL);
            loadIOSList();
            }
        }else if (j>=0){
            Android sp = new Android();
            sp.setMaSanPham( modelADNROID.getValueAt(j, 0).toString());
            sp.setTenSanPham(modelADNROID.getValueAt(j, 1).toString());
            sp.setDonGia(Float.valueOf(modelADNROID.getValueAt(j, 3).toString()));
            sp.setNamSX(Integer.valueOf(modelADNROID.getValueAt(j, 4).toString()));
            sp.setHangSanXuat(modelADNROID.getValueAt(j, 5).toString());
            String sl = JOptionPane.showInputDialog("Nhập số lượng");
            String tonkho = modelADNROID.getValueAt(j, 2).toString();
            sp.setSoLuong(Integer.valueOf(sl));
            int newSL = Integer.valueOf(tonkho) - Integer.valueOf(sl);
            if(newSL < 0){
                JOptionPane.showMessageDialog(null, "Quá số lượng tồn kho! Mời bạn nhập lại số lượng");
            }else{
            modelGioHang = (DefaultTableModel) tableGioHang.getModel();
            modelGioHang.addRow(new Object[]{sp.getMaSanPham(), sp.getTenSanPham(), sl, sp.getDonGia(), sp.getNamSX(),sp.getHangSanXuat()});
            list.add(sp);
            BLLsp.BLLsuaSLAND(sp,newSL);
            loadANDROIDList();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    public void loadIOSList(){
        modelIOS = new DefaultTableModel();
        modelIOS.addColumn("Mã SP");
        modelIOS.addColumn("Tên sản phẩm");
        modelIOS.addColumn("Số lượng");
        modelIOS.addColumn("Đơn giá");
        modelIOS.addColumn("Năm SX");
        modelIOS.addColumn("Phiên bản");
        modelIOS.addColumn("Img");
        tableIOS.setModel(modelIOS);
        column1 = tableIOS.getColumnModel().getColumn(1);
        column1.setPreferredWidth(150);
        ArrayList<DTOSanPham> arr = new ArrayList<DTOSanPham>();
        arr = BLLsp.BLLgetIOS();
        for(int i = 0; i < arr.size(); i++){
            DTOSanPham sp = arr.get(i);
            if(sp instanceof iOS){
                iOS ios = (iOS) sp;
                String masp = ios.getMaSanPham();
                String tensp = ios.getTenSanPham();
                Integer sl = ios.getSoLuong();
                Float dongia = ios.getDonGia();
                Integer nsx = ios.getNamSX();
                Float pb = ios.getPhienbanios();
                String img = ios.getImg();
                Object[] row = {masp,tensp,sl,dongia,nsx,pb,img};
                modelIOS.addRow(row);
            }
        }
    }
    
    public void loadANDROIDList(){
        modelADNROID = new DefaultTableModel();
        modelADNROID.addColumn("Mã SP");
        modelADNROID.addColumn("Tên sản phẩm");
        modelADNROID.addColumn("Số lượng");
        modelADNROID.addColumn("Đơn giá");
        modelADNROID.addColumn("Năm SX");
        modelADNROID.addColumn("Hãng");
        modelADNROID.addColumn("Img");
        tableANDROID.setModel(modelADNROID);
        column1 = tableANDROID.getColumnModel().getColumn(1);
        column1.setPreferredWidth(200);
        ArrayList<DTOSanPham> arr = new ArrayList<DTOSanPham>();
        arr = BLLsp.BLLgetANDROID();
        for(int i = 0; i < arr.size(); i++){
            DTOSanPham sp = arr.get(i);
            if(sp instanceof Android){
                Android and = (Android) sp;
                String masp = and.getMaSanPham();
                String tensp = and.getTenSanPham();
                Integer sl = and.getSoLuong();
                Float dongia = and.getDonGia();
                Integer nsx = and.getNamSX();
                String hang = and.getHangSanXuat();
                String img = and.getImg();
                Object[] row = {masp,tensp,sl,dongia,nsx,hang,img};
                modelADNROID.addRow(row);
            }
        }
    }
    
    private void buttonBoHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBoHangActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableGioHang.getModel();
        int i = tableGioHang.getSelectedRow();
            if (i >= 0) {
            iOS spIOS = new iOS();
            Android spAndroid = new Android();
            iOS ios = BLLsp.BLLtimIOS(model.getValueAt(i, 0).toString());
            if(ios != null){
                spIOS.setMaSanPham(model.getValueAt(i, 0).toString());
                int sl = ios.getSoLuong();
                int slGH = Integer.valueOf(model.getValueAt(i, 2).toString());
                int slupdate = sl + slGH;
                BLLsp.BLLsuaSLIOS(spIOS, slupdate);
                loadIOSList();
                list.remove(spIOS);
            }
            Android and = BLLsp.BLLtimANDROID(model.getValueAt(i, 0).toString());
            if(and != null){
                spAndroid.setMaSanPham(model.getValueAt(i, 0).toString());
                int sl = and.getSoLuong();
                int slGH = Integer.valueOf(model.getValueAt(i, 2).toString());
                int slupdate = sl + slGH;
                BLLsp.BLLsuaSLAND(spAndroid, slupdate);
                loadANDROIDList();
                list.remove(spAndroid);
            }
            model.removeRow(i);
        }
        
    }//GEN-LAST:event_buttonBoHangActionPerformed

    private void buttonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThanhToanActionPerformed
        // TODO add your handling code here:
        if(textTenKH.getText().isEmpty() || textDiaChi.getText().isEmpty() || textSDT.getText().isEmpty() || textMaKH.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin khách hàng");
        }else{
            GUIHoaDonBanHang gui_hdbh = new GUIHoaDonBanHang(textTenKH.getText().toString(),conboboxGender.getSelectedItem().toString(),textDiaChi.getText().toString(),Integer.valueOf(textSDT.getText()));
            gui_hdbh.setVisible(true);
            DTOKhachHang kh = new DTOKhachHang();
            kh.setMaKH(textMaKH.getText());
            kh.setTenKH(textTenKH.getText());
            kh.setGender((String) conboboxGender.getSelectedItem());
            kh.setDiaChi(textDiaChi.getText());
            kh.setSDT(textSDT.getText());
            DTOKhachHang checkKH = BLLkh.BLLtim(textMaKH.getText());
            if(checkKH == null){
                BLLkh.BLLthem(kh); 
            }
        }   
    }//GEN-LAST:event_buttonThanhToanActionPerformed

    private void tableIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableIOSMouseClicked
        // TODO add your handling code here:
        labelIMG.setText("");
        modelIOS = (DefaultTableModel) tableIOS.getModel();
        int i = tableIOS.getSelectedRow();
        if(i>=0){
            String fileimg = (String) modelIOS.getValueAt(i, 6).toString().trim();
            ImageIcon imageIcon = new ImageIcon(fileimg);
            Image scaledImage = imageIcon.getImage().getScaledInstance(labelIMG.getWidth(), labelIMG.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
            labelIMG.setIcon(scaledImageIcon);
        }
        tableANDROID.clearSelection();
    }//GEN-LAST:event_tableIOSMouseClicked

    private void tableANDROIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableANDROIDMouseClicked
        // TODO add your handling code here:
        labelIMG.setText("");
        modelADNROID = (DefaultTableModel) tableANDROID.getModel();
        int i = tableANDROID.getSelectedRow();
        if(i>=0){
            String fileimg = (String) modelADNROID.getValueAt(i, 6).toString().trim();
            ImageIcon imageIcon = new ImageIcon(fileimg);
            Image scaledImage = imageIcon.getImage().getScaledInstance(labelIMG.getWidth(), labelIMG.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
            labelIMG.setIcon(scaledImageIcon);
        }
        tableIOS.clearSelection();
    }//GEN-LAST:event_tableANDROIDMouseClicked

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
        DTOSanPham sp = BLLsp.BLLtimSP(textSearch.getText().trim());
        if(sp instanceof iOS && sp != null){
            iOS ios = (iOS) sp;
            modelIOS = new DefaultTableModel();
            modelIOS.addColumn("Mã sản phẩm");
            modelIOS.addColumn("Tên sản phẩm");
            modelIOS.addColumn("Số lượng ");
            modelIOS.addColumn("Đơn giá");
            modelIOS.addColumn("Năm sản xuất");
            modelIOS.addColumn("Phiên bản");
            tableIOS.setModel(modelIOS);
            Object[] row = {ios.getMaSanPham(),ios.getTenSanPham(),ios.getSoLuong(),ios.getDonGia(),ios.getNamSX(),ios.getPhienbanios()};
            modelIOS.addRow(row);            
        } else if(sp instanceof Android && sp != null){
            Android and = (Android) sp;
            modelADNROID = new DefaultTableModel();
            modelADNROID.addColumn("Mã sản phẩm");
            modelADNROID.addColumn("Tên sản phẩm");
            modelADNROID.addColumn("Số lượng ");
            modelADNROID.addColumn("Đơn giá");
            modelADNROID.addColumn("Năm sản xuất");
            modelADNROID.addColumn("Hãng");
            tableANDROID.setModel(modelADNROID);
            Object[] row = {and.getMaSanPham(),and.getTenSanPham(),and.getSoLuong(),and.getDonGia(),and.getNamSX(),and.getHangSanXuat()};
            modelADNROID.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã sản phẩm");
        }
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadANDROIDList();
        loadIOSList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textSearchMouseClicked
        // TODO add your handling code here:
        textSearch.setText("");
    }//GEN-LAST:event_textSearchMouseClicked

    private void textSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void buttonSearchMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchMaKHActionPerformed
        // TODO add your handling code here:
        DTOKhachHang khm = BLLkh.BLLtim(textMaKH.getText());
            if(khm != null){
                textMaKH.setText(khm.getMaKH());
                textTenKH.setText(khm.getTenKH());
                textDiaChi.setText(khm.getDiaChi());
                textSDT.setText(khm.getSDT());
                conboboxGender.setSelectedItem(khm.getGender());
        }
    }//GEN-LAST:event_buttonSearchMaKHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUITrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonBoHang;
    private javax.swing.JButton buttonHD;
    private javax.swing.JButton buttonKH;
    private javax.swing.JButton buttonNCC;
    private javax.swing.JButton buttonNV;
    private javax.swing.JButton buttonPN;
    private javax.swing.JButton buttonSP;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonSearchMaKH;
    private javax.swing.JButton buttonThanhToan;
    private javax.swing.JComboBox<String> conboboxGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel labelIMG;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPanel panelHinhAnh;
    private javax.swing.JPanel panelKhachHang;
    private javax.swing.JTable tableANDROID;
    private javax.swing.JTable tableGioHang;
    private javax.swing.JTable tableIOS;
    private javax.swing.JTextField textDiaChi;
    private javax.swing.JTextField textMaKH;
    private javax.swing.JTextField textSDT;
    private javax.swing.JTextField textSearch;
    private javax.swing.JTextField textTenKH;
    // End of variables declaration//GEN-END:variables
}
